### ISSUE TITLE
Wrong like and comment count

### ISSUE THREAD

**Issue by aboveStars** [aboveStars/blocksocial-v2-frontend#7]
When user see post from feed there is no problem likes, comments and their counts but when go some user page there are missing or false information about them (likes, comments, counts).

**Comment by aboveStars** [comment]
I couldn't find the problem at first look. But most probably "getServerSideProps" not waiting to load all posts and returns the page without needed post datas like comment and like count

**Comment by aboveStars** [comment]
Now it is working very well without making anything.  So I think it is related with connection quality.

**Comment by aboveStars** [comment]
But after all, I am sure all problems like this come around due to my bad database structure. It is so nested. Some critical operations which have more then one step, conducting with client rather than server. They should be conducted by "cloud functions" or something like that.

**Comment by aboveStars** [comment]
Now it is on "home" page but not on "user" page.

**Comment by aboveStars** [comment]
When "main" page shows, "useEffect" works a few times before "current" user informations loads. So if a user is popular, user sees himself or herself for a second. (normally a user shouldn't see him or herself). After some regulations to useEffect, seems everything normal. Also there are so many type errors. (I forgot to update these types after I updated old types)

**Comment by aboveStars** [comment]
After editing 'useEffect' a bit, I thought this problem is solved but nope. It is just happens less often. I think it is about 'postFront's 'useEffect' When "currentUser" changes, 'postFront' like status ( if we like ) remains same.

**Comment by aboveStars** [comment]
I think, I found the problem. It is about "key" prop of "PostItem". After switching from main page to user page, as I use "index" for "key", some "not-same" posts have "same" "key". So react, not updating this post and its datas.

**Comment by aboveStars** [comment]
`I think, I found the problem. It is about "key" prop of "PostItem". After switching from main page to user page, as I use "index" for "key", some "not-same" posts have same "key". So react, not updating this post and its datas.`
No anomalies after "key" update to each post.

**Comment by aboveStars** [comment]
Still no anomalies.

**Comment by aboveStars** [comment]
Using "too" unique "keys" like "Date.now()" is causing unnecessary refreshing.

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by naudachu** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @Uitalo, @pmdaly, @avatar-lavventura, @SourceAura, @ilya0x, @kallydev, @prabal-ds

**Comment by WelderOliveira** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @byob75, @bonkrat, @marc23gold, @RohitLakh, @mattiauliano, @mani3h, @YvesToiser

**Comment by havi23** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

am11001, @ziyahan, @snakewarhead, @SuperHero123123, @Ilingu, @taishi8117, @dvntaudio, @ArpitxGit, @rkarabut, @cty12, @0xV01, @jameshih, @TheKingShun, @david-dacruz, @swagkarna, @LiliWeiSE, @aldk98, @lulinglingcufe, @xchanmolx, @zoeronen

**Comment by rohitsonawat** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
aulon97, @cs-fedy, @Stephayo, @OGPey, @akshatcoder-hash, @dbcakadbc, @zhuangjun, @Pteus, @jasont7, @aideneng87, @newagency, @dsky1990, @b-doroszuk, @jester91, @ilikeseafood, @gowtham-siddharth, @asankaSovis, @Badiru27, @TusharTyagi91, @FirasHadjAmeur

**Comment by leichenlager** [comment]
Hello, 
I received a phishing email that was supposedly a 'developer position' with GitHub and they used your username. Looks like they rewrote the issue and used it to craft the phishing mail to look authentic or plausible.  Just thought you should know this.

**Comment by b-doroszuk** [comment]
Hey thanks,
I have noticed it was phishing 😉
But really appreciate the warning
Thx bro

W dniu wt., 20.02.2024 o 20:25 leichenlager ***@***.***>
napisał(a):

**Comment by leichenlager** [comment]
No problem… We Humans have to look out for each other especially nowadays.
Enjoy your day!
